### ISSUE TITLE
compareTo is incorrect

### ISSUE THREAD

**Issue by jbrucker** [OOP2018/coinpurse-ploykwan#7]
Compare 
b1 = new BankNote(1, "USD");
b2 = new BankNote(2, "USD");

what's the result?

**Comment by ploykwan** [comment]
<img width="382" alt="screen shot 2561-02-14 at 09 01 14" src="https://user-images.githubusercontent.com/25145746/36184335-a98a6092-1165-11e8-98a7-2d42756fdecd.png">
